import { useState } from 'react'
import { useApp, money, formatDate } from '../context/AppContext'
import { PageHeader, StatusBadge, Modal, EmptyState } from '../components'

export default function Payments() {
  const { user, bookings, services, updateBooking, payService } = useApp(); const [pay, setPay] = useState(null); const [method, setMethod] = useState('')
  const items = [...bookings.filter(x => x.userId === user.id).map(x => ({ ...x, ref: x.id, vehicle: x.vehicleNumber, type: 'Parking', amount: x.total, date: x.entry })), ...services.filter(x => x.userId === user.id).map(x => ({ ...x, ref: x.id, vehicle: x.vehicleNumber, type: 'Service', amount: x.cost, date: x.date, paymentStatus: x.paymentStatus || 'Pending' }))]
  const openPayment = item => { setPay(item); setMethod('') }
  const confirm = () => { if (!pay || !method) return; if (pay.type === 'Parking') updateBooking(pay.id, { paymentStatus: 'Paid', paymentMethod: method }); else payService(pay.id); setPay(null); setMethod('') }
  return <><PageHeader eyebrow="MONEY, CLEARLY" title="Payments & invoices" description="A simple record of what you have booked and paid for." /><section className="panel table-panel"><div className="table-head payment-head"><span>Invoice</span><span>Type</span><span>Vehicle</span><span>Amount</span><span>Payment</span><span></span></div>{items.map(item => <div className="table-row payment-row" key={item.ref}><span><strong>INV-{item.ref}</strong><small>{formatDate(item.date)}</small></span><span>{item.type}</span><span>{item.vehicle}</span><span>{money(item.amount)}</span><StatusBadge>{item.paymentStatus}</StatusBadge>{item.paymentStatus === 'Pending' ? <button className="button small coral" onClick={() => openPayment(item)}>Pay now</button> : <button className="text-button">View invoice</button>}</div>)}{!items.length && <EmptyState title="No payments yet" text="Parking and service invoices will appear here." />}</section>{pay && <Modal title="Confirm payment" onClose={() => setPay(null)}><p>Complete the simulated payment of <strong>{money(pay.amount)}</strong> for {pay.ref}.</p><div className="payment-methods">{['UPI', 'Card', 'Cash'].map(option => <button className={method === option ? 'selected' : ''} key={option} onClick={() => setMethod(option)}>{option}</button>)}</div>{!method && <p className="error">Choose a payment method to continue.</p>}<button className="button coral full" disabled={!method} onClick={confirm}>Confirm payment <span>↗</span></button></Modal>}</>
}
