import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useApp } from '../context/AppContext'
import { PageHeader, Field, FieldError } from '../components'

export default function Profile() {
  const { user, vehicles, bookings, updateProfile, changePassword } = useApp()
  const [form, setForm] = useState({ name: user.name || '', phone: user.phone || '', city: user.city || 'Pune, Maharashtra', address: user.address || '' })
  const [passwordForm, setPasswordForm] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' })
  const [error, setError] = useState(''); const [saved, setSaved] = useState(false); const [passwordError, setPasswordError] = useState(''); const [passwordSaved, setPasswordSaved] = useState(false); const [photoUrl, setPhotoUrl] = useState(user.profilePhoto || '')
  useEffect(() => () => { if (photoUrl.startsWith('blob:')) URL.revokeObjectURL(photoUrl) }, [photoUrl])
  const change = event => { setSaved(false); setForm(current => ({ ...current, [event.target.name]: event.target.value })) }
  const submit = event => { event.preventDefault(); const name = form.name.trim(); const phone = form.phone.replace(/\D/g, ''); const city = form.city.trim(); const address = form.address.trim(); if (!name || !city || !address) return setError('Name, city and address are required.'); if (!/^\d{10}$/.test(phone)) return setError('Enter a valid 10-digit Indian mobile number.'); setError(''); updateProfile({ name, phone, city, address }); setForm({ name, phone, city, address }); setSaved(true) }
  const changePasswordField = event => { setPasswordSaved(false); setPasswordForm(current => ({ ...current, [event.target.name]: event.target.value })) }
  const submitPassword = event => { event.preventDefault(); if (passwordForm.newPassword !== passwordForm.confirmPassword) return setPasswordError('New password and confirmation do not match.'); const result = changePassword(passwordForm.currentPassword, passwordForm.newPassword); if (result.error) return setPasswordError(result.error); setPasswordError(''); setPasswordForm({ currentPassword: '', newPassword: '', confirmPassword: '' }); setPasswordSaved(true) }
  const uploadPhoto = event => { const file = event.target.files[0]; if (!file) return; const preview = URL.createObjectURL(file); setPhotoUrl(preview); const reader = new FileReader(); reader.onload = () => updateProfile({ profilePhoto: reader.result }); reader.readAsDataURL(file) }
  const removePhoto = () => { if (photoUrl.startsWith('blob:')) URL.revokeObjectURL(photoUrl); setPhotoUrl(''); updateProfile({ profilePhoto: '' }) }
  const defaultVehicle = vehicles.find(vehicle => vehicle.isDefault)
  return <><PageHeader eyebrow="YOUR ACCOUNT" title="Profile" description="Your ParkSmart identity and activity at a glance." /><div className="profile-grid"><section className="panel profile-card"><div className="profile-avatar">{photoUrl ? <img src={photoUrl} alt="Profile" /> : user.name[0]}</div><label className="photo-upload">Upload photo<input type="file" accept="image/*" onChange={uploadPhoto} /></label>{photoUrl && <button type="button" className="text-button" onClick={removePhoto}>Remove photo</button>}<h2>{user.name}</h2><p>{user.email}</p><span className="role-pill">Customer</span><div className="profile-lines"><span>Member since <strong>September 2026</strong></span><span>Vehicles <strong>{vehicles.length}</strong></span><span>Bookings <strong>{bookings.filter(x => x.userId === user.id).length}</strong></span></div><div className="default-vehicle"><span className="eyebrow">DEFAULT VEHICLE</span>{defaultVehicle ? <><strong>{defaultVehicle.vehicleNumber}</strong><small>{defaultVehicle.brand} {defaultVehicle.model} · {defaultVehicle.color}</small></> : <small>No default vehicle selected.</small>}<Link to="/vehicles">Manage vehicles</Link></div></section><div className="profile-stack"><form className="panel profile-form" onSubmit={submit}><span className="eyebrow">PERSONAL DETAILS</span><h2>Account information</h2><Field label="Full name"><input name="name" value={form.name} onChange={change} /></Field><Field label="Email address"><input value={user.email} disabled /></Field><Field label="Phone number"><input name="phone" value={form.phone} onChange={change} placeholder="9876543210" /></Field><Field label="City"><input name="city" value={form.city} onChange={change} /></Field><Field label="Address line"><input name="address" value={form.address} onChange={change} placeholder="Street or area" /></Field>{error && <FieldError>{error}</FieldError>}{saved && <p className="success">Profile changes saved.</p>}<button className="button dark">Save changes</button></form><form className="panel profile-form" onSubmit={submitPassword}><span className="eyebrow">SECURITY</span><h2>Change password</h2><Field label="Current password"><input type="password" name="currentPassword" value={passwordForm.currentPassword} onChange={changePasswordField} required /></Field><Field label="New password"><input type="password" name="newPassword" value={passwordForm.newPassword} onChange={changePasswordField} minLength="4" required /></Field><Field label="Confirm new password"><input type="password" name="confirmPassword" value={passwordForm.confirmPassword} onChange={changePasswordField} required /></Field>{passwordError && <FieldError>{passwordError}</FieldError>}{passwordSaved && <p className="success">Password changed successfully.</p>}<button className="button dark">Update password</button></form></div></div></>
}
