import { useState } from 'react'
import { useApp } from '../context/AppContext'
import { PageHeader, Field, Modal, ConfirmDialog, SearchBar, EmptyState } from '../components'
const blank = { vehicleNumber: '', vehicleType: 'Car', brand: '', model: '', color: '', fuelType: 'Petrol', ownerName: '', isDefault: false }

function VehicleForm({ initial, onSave, onClose }) {
  const [form, setForm] = useState(initial || blank); const [errors, setErrors] = useState({})
  const update = event => setForm(current => ({ ...current, [event.target.name]: event.target.value }))
  const submit = event => { event.preventDefault(); const clean = Object.fromEntries(Object.entries(form).map(([key, value]) => [key, typeof value === 'string' ? value.trim() : value])); const nextErrors = {}; if (!/^[A-Z]{2}\d{2}[A-Z]{1,2}\d{4}$/.test(clean.vehicleNumber.toUpperCase())) nextErrors.vehicleNumber = 'Enter a valid vehicle number, e.g. MH12AB1234.'; ['brand', 'model', 'color', 'ownerName'].forEach(field => { if (!clean[field]) nextErrors[field] = 'This field is required.' }); if (Object.keys(nextErrors).length) return setErrors(nextErrors); onSave({ ...clean, vehicleNumber: clean.vehicleNumber.toUpperCase(), isDefault: initial?.isDefault || false }); onClose() }
  return <Modal title={initial ? 'Edit vehicle' : 'Add a vehicle'} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><Field label="Vehicle number" error={errors.vehicleNumber}><input name="vehicleNumber" value={form.vehicleNumber} onChange={update} placeholder="MH12AB1234" /></Field><Field label="Vehicle type"><select name="vehicleType" value={form.vehicleType} onChange={update}><option>Car</option><option>Bike</option></select></Field><Field label="Brand" error={errors.brand}><input name="brand" value={form.brand} onChange={update} /></Field><Field label="Model" error={errors.model}><input name="model" value={form.model} onChange={update} /></Field><Field label="Color" error={errors.color}><input name="color" value={form.color} onChange={update} /></Field><Field label="Fuel type"><select name="fuelType" value={form.fuelType} onChange={update}>{['Petrol', 'Diesel', 'EV', 'CNG'].map(x => <option key={x}>{x}</option>)}</select></Field><Field label="Owner name" error={errors.ownerName}><input name="ownerName" value={form.ownerName} onChange={update} /></Field></div><p className="muted form-hint">Use format like MH12AB1234.</p><div className="modal-actions"><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button coral">Save vehicle</button></div></form></Modal>
}
export default function Vehicles() { const { vehicles, saveVehicle, deleteVehicle, setDefaultVehicle } = useApp(); const [search, setSearch] = useState(''); const [editing, setEditing] = useState(null); const [remove, setRemove] = useState(null); const filtered = vehicles.filter(v => `${v.vehicleNumber} ${v.brand} ${v.model}`.toLowerCase().includes(search.toLowerCase())); return <><PageHeader eyebrow="YOUR GARAGE" title="My vehicles" description="Keep your vehicles ready for their next journey." action={<button className="button coral" onClick={() => setEditing({})}>+ Add vehicle</button>} /><div className="toolbar"><SearchBar value={search} onChange={setSearch} placeholder="Search by number, brand or model" /><span className="result-count">{filtered.length} vehicles</span></div><div className="vehicle-grid">{filtered.map(vehicle => <article className={`vehicle-card ${vehicle.isDefault ? 'default' : ''}`} key={vehicle.id}><div className="vehicle-top"><span className="vehicle-type">{vehicle.vehicleType === 'Car' ? '▰' : '▲'}</span>{vehicle.isDefault && <span className="default-tag">DEFAULT</span>}<button className="more-button">•••</button></div><h2>{vehicle.vehicleNumber}</h2><p>{vehicle.brand} {vehicle.model} <span>·</span> {vehicle.color}</p><div className="vehicle-specs"><span>Fuel <strong>{vehicle.fuelType}</strong></span><span>Owner <strong>{vehicle.ownerName}</strong></span></div><div className="vehicle-actions"><button onClick={() => setEditing(vehicle)}>Edit</button><button onClick={() => setRemove(vehicle)}>Delete</button>{!vehicle.isDefault && <button onClick={() => setDefaultVehicle(vehicle.id)}>Set default</button>}</div></article>)}{!filtered.length && <EmptyState title="No vehicles found" text="Add your first vehicle to start booking parking and services." />}</div>{editing && <VehicleForm initial={editing.id ? editing : null} onSave={saveVehicle} onClose={() => setEditing(null)} />}{remove && <ConfirmDialog title="Remove vehicle?" text={`This will remove ${remove.vehicleNumber} from your garage.`} onConfirm={() => { deleteVehicle(remove.id); setRemove(null) }} onClose={() => setRemove(null)} />}</> }
