import { NavLink, Navigate, useNavigate } from 'react-router-dom'
import { useApp, money } from './context/AppContext'

export function ProtectedRoute({ children, role }) { const { user } = useApp(); if (!user) return <Navigate to="/login" replace />; if (role && user.role !== role) return <Navigate to={user.role === 'admin' ? '/admin/dashboard' : '/dashboard'} replace />; return children }
export function StatusBadge({ children }) { return <span className={`status status-${String(children).toLowerCase().replaceAll(' ', '-')}`}>{children}</span> }
export function PageHeader({ eyebrow, title, description, action }) { return <div className="page-header"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description && <p>{description}</p>}</div>{action}</div> }
export function EmptyState({ icon = '◌', title, text }) { return <div className="empty"><strong>{icon}</strong><h3>{title}</h3><p>{text}</p></div> }
export function StatCard({ label, value, note, icon, tone = '' }) { return <div className={`stat-card ${tone}`}><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></div> }
export function Modal({ title, children, onClose }) { return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={onClose}>×</button></div>{children}</div></div> }
export function ConfirmDialog({ title, text, onConfirm, onClose }) { return <Modal title={title} onClose={onClose}><p>{text}</p><div className="modal-actions"><button className="button ghost" onClick={onClose}>Keep</button><button className="button danger" onClick={onConfirm}>Confirm</button></div></Modal> }
function links(role) { return role === 'admin' ? [{ to: '/admin/dashboard', label: 'Overview', icon: '⌂' }, { to: '/admin/slots', label: 'Parking slots', icon: '▦' }, { to: '/admin/bookings', label: 'Bookings', icon: '◷' }, { to: '/admin/services', label: 'Services', icon: '✦' }] : [{ to: '/dashboard', label: 'Overview', icon: '⌂' }, { to: '/vehicles', label: 'My vehicles', icon: '▣' }, { to: '/parking', label: 'Find parking', icon: '⌖' }, { to: '/bookings', label: 'My bookings', icon: '◷' }, { to: '/service-booking', label: 'Book a service', icon: '✦' }, { to: '/service-history', label: 'Service history', icon: '↗' }, { to: '/payments', label: 'Payments', icon: '₹' }, { to: '/profile', label: 'Profile', icon: '○' }] }
export function AppShell({ children }) { const { user, logout } = useApp(); const navigate = useNavigate(); const items = links(user.role); return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span><span>Park<span>Smart</span></span></div><div className="user-chip"><div className="avatar">{user.name[0]}</div><div><strong>{user.name}</strong><small>{user.role === 'admin' ? 'Operations admin' : 'Customer account'}</small></div></div><nav>{items.map(item => <NavLink key={item.to} to={item.to} className={({ isActive }) => isActive ? 'active' : ''}><span>{item.icon}</span>{item.label}</NavLink>)}</nav><button className="logout" onClick={() => { logout(); navigate('/') }}>↪ <span>Sign out</span></button></aside><main className="main"><header className="topbar"><div className="mobile-brand"><span className="brand-mark">P</span> ParkSmart</div><span className="location-pill">⌖ Pune, Maharashtra</span><div className="top-actions"><button className="icon-button">◔</button><div className="avatar small">{user.name[0]}</div></div></header><div className="content">{children}</div></main></div> }
export function LandingNav() { const { user } = useApp(); return <header className="landing-nav"><div className="brand"><span className="brand-mark">P</span><span>Park<span>Smart</span></span></div><div className="landing-links"><a href="#features">Why ParkSmart</a><a href="#how">How it works</a></div><div className="landing-actions">{user ? <NavLink className="button dark" to={user.role === 'admin' ? '/admin/dashboard' : '/dashboard'}>Open dashboard</NavLink> : <><NavLink className="text-link" to="/login">Sign in</NavLink><NavLink className="button dark" to="/register">Get started <span>↗</span></NavLink></>}</div></header> }
export function FieldError({ children }) { return children ? <small className="error field-error">{children}</small> : null }
export function Field({ label, error, children, ...props }) { return <label className="field"><span>{label}</span>{children || <input {...props} />}<FieldError>{error}</FieldError></label> }
export function SearchBar({ value, onChange, placeholder = 'Search...' }) { return <label className="search"><span>⌕</span><input value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} /></label> }
export function BookingRow({ booking, onClick }) { return <button className="table-row" onClick={onClick}><span><strong>{booking.id}</strong><small>{booking.vehicleNumber}</small></span><span>{booking.slotId}</span><span>{booking.duration} hrs</span><span>{money(booking.total)}</span><StatusBadge>{booking.status}</StatusBadge></button> }
